project_name: dev

before:
  hooks:
    - go mod tidy

builds:
  - id: dev
    dir: "."
    main: "."
    binary: dev
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=loopvar
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"

brews:
  - repository:
      owner: FollowTheProcess
      name: homebrew-tap
      token: "{{.Env.HOMEBREW_TAP_TOKEN}}"
    goarm: "7"
    folder: Formula
    commit_author:
      name: Tom Fleet
      email: tomfleet2018@gmail.com
    homepage: https://github.com/FollowTheProcess/dev
    description: The all in one developer toolkit
    license: Apache Software License 2.0
    install: |
      bin.install "dev"
    test: |
      "#{bin}/dev --version"

archives:
  - id: dev
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

sboms:
  - id: dev
    artifacts: archive
    documents:
      - >-
        {{ .ProjectName }}-
        {{- .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}.sbom

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Tag }}-dev{{ .ShortCommit }}"

changelog:
  # The changelog is handled by release drafter
  skip: true
